### ISSUE TITLE
How can i specify which browser to use?

### ISSUE THREAD

**Issue by lzhelisichka** [Ardesco/Selenium-Maven-Template#12]
Hello!
It's really cool, but, please, help me: how can i specify which browser to use?
Where and how should I specify the option to use one browser, for example, google chrome, or several at once? Now every time i have message that it use browser by default.

**Comment by Ardesco** [comment]
As stated in the Readme:

Anything else?

Yes you can specify which browser to use by using one of the following switches:

-Dbrowser=firefox
-Dbrowser=chrome
-Dbrowser=ie
-Dbrowser=opera
-Dbrowser=htmlunit
-Dbrowser=phantomjs

You can only use one browser at a time (You can spin up multiple copies of that browser though).  You can run different browser switches in different console windows to get more than one browser type running at the same time.
