### ISSUE TITLE
System Property Variables not being picked up

### ISSUE THREAD

**Issue by mse-rspenceley** [Ardesco/Selenium-Maven-Template#15]
Hi

No matter what I do, when doing mvn test I always get:

'The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html'

I even went to the extent of having my test do

```java
System.out.println("TEST: " + System.getProperty("webdriver.chrome.driver");
```

This just spits out "TEST: null" when ran.

This even happens with your exact pom file

Running Maven 3.3.3

**Comment by Ardesco** [comment]
Try a: 

    mvn clean install

the driver-binary-downloader-maven-plugin runs in the test-compile phase.  This should be triggered by a `mvn test` but it's possible it's not happening in your case.  You could also try:

    mvn test-compile test

Can you provide the output from your console?

**Comment by mse-rspenceley** [comment]
Sorry, didn't get back to this as was too busy at work.

So, I've got the following in my pom file

```xml
<plugin>
            <groupId>com.lazerycode.selenium</groupId>
            <artifactId>driver-binary-downloader-maven-plugin</artifactId>
            <version>1.0.7</version>
            <configuration>
               <overwriteFilesThatExist>false</overwriteFilesThatExist>
               <rootStandaloneServerDirectory>${standalone.binary.root.folder}</rootStandaloneServerDirectory>
               <downloadedZipFileDirectory>${project.basedir}/src/test/resources/selenium_standalone_zips</downloadedZipFileDirectory>
            </configuration>
            <executions>
               <execution>
                  <goals>
                     <goal>selenium</goal>
                  </goals>
               </execution>
            </executions>
         </plugin>
<plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-failsafe-plugin</artifactId>
            <version>2.19</version>
            <dependencies>
               <dependency>
                  <groupId>org.apache.maven.surefire</groupId>
                  <artifactId>surefire-junit47</artifactId>
                  <version>2.19</version>
               </dependency>
            </dependencies>
            <configuration>
               <systemPropertyVariables>
                  <phantomjs.binary.path>${phantomjs.binary.path}</phantomjs.binary.path>
                  <webdriver.chrome.driver>${webdriver.chrome.driver}</webdriver.chrome.driver>
                  <webdriver.ie.driver>${webdriver.ie.driver}</webdriver.ie.driver>
                  <webdriver.opera.driver>${webdriver.opera.driver}</webdriver.opera.driver>
               </systemPropertyVariables>
               <testFailureIgnore>true</testFailureIgnore>
            </configuration>
            <executions>
               <execution>
                  <id>integration-test</id>
                  <goals>
                     <goal>integration-test</goal>
                     <goal>verify</goal>
                  </goals>
               </execution>
            </executions>
         </plugin>
```

When I run, I get the following in my console
```sh
[INFO] 
[INFO] <<< driver-binary-downloader-maven-plugin:1.0.7:selenium (default) < test-compile @ player-based-testing <<<
[INFO] 
[INFO] --- driver-binary-downloader-maven-plugin:1.0.7:selenium (default) @ player-based-testing ---
[INFO]  
[INFO] --------------------------------------------------------
[INFO]  DOWNLOADING SELENIUM STAND-ALONE EXECUTABLE BINARIES...
[INFO] --------------------------------------------------------
[INFO]  
[INFO] Only get drivers for current Operating System: true
[INFO] Getting drivers for current operating system only.
[INFO] Archives will be downloaded to '/Users/richard.spenceley/rcf-ui-automation-testing/src/test/resources/selenium_standalone_zips'
[INFO] Standalone executable files will be extracted to '/Users/richard.spenceley/rcf-ui-automation-testing/selenium_standalone'
[INFO]  
[INFO] Preparing to download Selenium Standalone Executable Binaries...
[INFO] Binary 'operadriver' Exists: true
[INFO] Binary 'phantomjs' Exists: true
[INFO] Binary 'chromedriver' Exists: true
[INFO] Setting maven property - ${webdriver.opera.driver} = /Users/richard.spenceley/rcf-ui-automation-testing/selenium_standalone/osx/operachromium/64bit/operadriver
[INFO] Setting maven property - ${phantomjs.binary.path} = /Users/richard.spenceley/rcf-ui-automation-testing/selenium_standalone/osx/phantomjs/64bit/phantomjs
[INFO] Setting maven property - ${webdriver.chrome.driver} = /Users/richard.spenceley/rcf-ui-automation-testing/selenium_standalone/osx/googlechrome/64bit/chromedriver
[INFO]  
[INFO] --------------------------------------------------------
[INFO] SELENIUM STAND-ALONE EXECUTABLE DOWNLOADS COMPLETE
[INFO] --------------------------------------------------------
[INFO]  
[INFO] 
[INFO] --- maven-failsafe-plugin:2.19:integration-test (integration-test) @ player-based-testing ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=2048m; support was removed in 8.0
@audio
Feature: Audio playing inside RCF
  As a digital producer,
  I want audio to work inside RCF,
  So I can make activities that involve audio
Running Scenario: Checking that audioContainer elements get an ID prefixed with the activity ID
TEST:/Users/richard.spenceley/rcf-ui-automation-testing/selenium_standalone/osx/googlechrome/64bit/chromedriver
```
The last line is still set to output the system property webdriver.chrome.driver
Whilst my Selenium Server shows the following:
```
09:19:27.885 INFO - Got a request to create a new session: Capabilities [{os=OS X, browserName=chrome, platform=MAC}]
09:19:27.885 INFO - Available nodes: [http://localhost:5555]
09:19:27.886 INFO - Trying to create a new session on node http://localhost:5555
09:19:27.886 INFO - Trying to create a new session on test slot {seleniumProtocol=WebDriver, os=OS X, browserName=chrome, maxInstances=1, platform=MAC}
09:19:27.909 INFO - Executing: [new session: Capabilities [{os=OS X, browserName=chrome, platform=MAC}]])
09:19:27.929 INFO - Creating a new session for Capabilities [{os=OS X, browserName=chrome, platform=MAC}]
09:19:27.967 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: java.lang.reflect.InvocationTargetException
Build info: version: '2.48.2', revision: '41bccdd10cf2c0560f637404c2d96164b67d9d67', time: '2015-10-09 13:08:06'
System info: host: 'L7333', ip: '10.101.117.91', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_51'
Driver info: driver.version: unknown
Caused by: java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.chrome.driver system property; for more information, see https://github.com/SeleniumHQ/selenium/wiki/ChromeDriver. The latest version can be downloaded from http://chromedriver.storage.googleapis.com/index.html
```

**Comment by Ardesco** [comment]
Well if you are able to log out the driver location using the system property webdriver.chrome.driver in your code, it looks like the binary downloader plugin has done its job and the property has been correctly passed in by the maven surefire plugin.  

Are you able to provide a link to your code that performs the driver initialisation?  My guess right now is that there something in that bit of code that either overwrites the system property, or uses another property to get the location of the driver binary?

**Comment by moha297** [comment]
I am getting the error too.
On logging I dont see the property getting picked up in code as well.

```shell
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Spark Automation 1.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ spark-automation ---
[INFO] Deleting /Users/anuraag/projects/Spark-Automation-Suite/target
[INFO] 
[INFO] --- properties-maven-plugin:1.0.0:read-project-properties (default) @ spark-automation ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ spark-automation ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/anuraag/projects/Spark-Automation-Suite/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ spark-automation ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ spark-automation ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ spark-automation ---
[INFO] Compiling 10 source files to /Users/anuraag/projects/Spark-Automation-Suite/target/test-classes
[INFO] 
[INFO] >>> driver-binary-downloader-maven-plugin:1.0.7:selenium (default) > test-compile @ spark-automation >>>
[INFO] 
[INFO] --- properties-maven-plugin:1.0.0:read-project-properties (default) @ spark-automation ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ spark-automation ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/anuraag/projects/Spark-Automation-Suite/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ spark-automation ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ spark-automation ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ spark-automation ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] <<< driver-binary-downloader-maven-plugin:1.0.7:selenium (default) < test-compile @ spark-automation <<<
[INFO] 
[INFO] --- driver-binary-downloader-maven-plugin:1.0.7:selenium (default) @ spark-automation ---
[INFO]  
[INFO] --------------------------------------------------------
[INFO]  DOWNLOADING SELENIUM STAND-ALONE EXECUTABLE BINARIES...
[INFO] --------------------------------------------------------
[INFO]  
[INFO]  file:/Users/anuraag/projects/Spark-Automation-Suite/src/test/resources/RepositoryMap.xml is valid
[INFO]  
[INFO] Only get drivers for current Operating System: true
[INFO] Getting drivers for current operating system only.
[INFO] Archives will be downloaded to '/Users/anuraag/projects/Spark-Automation-Suite/src/test/resources/selenium_standalone_zips'
[INFO] Standalone executable files will be extracted to '/Users/anuraag/projects/Spark-Automation-Suite/selenium_standalone'
[INFO]  
[INFO] Preparing to download Selenium Standalone Executable Binaries...
[INFO] Binary 'operadriver' Exists: true
[INFO] Binary 'phantomjs' Exists: true
[INFO] Binary 'chromedriver' Exists: true
[INFO] Setting maven property - ${webdriver.opera.driver} = /Users/anuraag/projects/Spark-Automation-Suite/selenium_standalone/osx/operachromium/64bit/operadriver
[INFO] Setting maven property - ${phantomjs.binary.path} = /Users/anuraag/projects/Spark-Automation-Suite/selenium_standalone/osx/phantomjs/64bit/phantomjs
[INFO] Setting maven property - ${webdriver.chrome.driver} = /Users/anuraag/projects/Spark-Automation-Suite/selenium_standalone/osx/googlechrome/64bit/chromedriver
[INFO]  
[INFO] --------------------------------------------------------
[INFO] SELENIUM STAND-ALONE EXECUTABLE DOWNLOADS COMPLETE
[INFO] --------------------------------------------------------
[INFO]  
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ spark-automation ---
[INFO] Surefire report directory: /Users/anuraag/projects/Spark-Automation-Suite/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.magnifi.selenium.tests.home.HomeScreenTest
Configuring TestNG with: org.apache.maven.surefire.testng.conf.TestNG652Configurator@36b29562
Instantiating the ApplicationProperties - listed below:
>>>>>>>>>TEST: null
 
```

**Comment by Ardesco** [comment]
Can you provide a link to your code so I can investigate.

**Comment by Ardesco** [comment]
Closing this off since there has been no response.  Feel free to reopen it if you can provide the information requested.

**Comment by sopansh** [comment]
Hi I am getting the same issue of driver not executable.

>host: ter$ mvn test -Dxml=testng.xml

`
[INFO] Scanning for projects...
[INFO] 
[INFO] -----------------< com.rakuten.dataplatform:DPD-Auto >------------------
[INFO] Building DPD-Auto 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:3.1.0:clean (auto-clean) @ DPD-Auto ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ DPD-Auto ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 17 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ DPD-Auto ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 37 source files to /Users/ts-sopan.a.shirdhonk/IdeaProjects/DPDAuto/target/classes
[INFO] /Users/ts-sopan.a.shirdhonk/IdeaProjects/DPDAuto/src/main/java/com/rakuten/dpd/apis/jsonCreator/BaseJsonCreator.java: /Users/ts-sopan.a.shirdhonk/IdeaProjects/DPDAuto/src/main/java/com/rakuten/dpd/apis/jsonCreator/BaseJsonCreator.java uses unchecked or unsafe operations.
[INFO] /Users/ts-sopan.a.shirdhonk/IdeaProjects/DPDAuto/src/main/java/com/rakuten/dpd/apis/jsonCreator/BaseJsonCreator.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ DPD-Auto ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ DPD-Auto ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 11 source files to /Users/ts-sopan.a.shirdhonk/IdeaProjects/DPDAuto/target/test-classes
[INFO] /Users/ts-sopan.a.shirdhonk/IdeaProjects/DPDAuto/src/test/java/com/rakuten/dpd/base/BaseTest.java: /Users/ts-sopan.a.shirdhonk/IdeaProjects/DPDAuto/src/test/java/com/rakuten/dpd/base/BaseTest.java uses unchecked or unsafe operations.
[INFO] /Users/ts-sopan.a.shirdhonk/IdeaProjects/DPDAuto/src/test/java/com/rakuten/dpd/base/BaseTest.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ DPD-Auto ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
dev
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.386 s
[INFO] Finished at: 2018-10-30T11:09:12+09:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project DPD-Auto: There are test failures.
[ERROR] 
[ERROR] Please refer to /Users/ts-sopan.a.shirdhonk/IdeaProjects/DPDAuto/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] There was an error in the forked process
[ERROR] The driver is not executable: /Users/ts-sopan.a.shirdhonk/IdeaProjects/DPDAuto/target/classes/utilityJars/geckodriver_mac
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] The driver is not executable: /Users/ts-sopan.a.shirdhonk/IdeaProjects/DPDAuto/target/classes/utilityJars/geckodriver_mac
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:656)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:282)
[ERROR]         at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:245)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1183)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
[ERROR]         at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
[ERROR]         at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
[ERROR]         at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]         at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]         at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]         at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]         at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]         at org.apache.maven.cli.MavenCli.execute(MavenCli.java:954)
[ERROR]         at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR]         at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR]         at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`

Below is my pom xml build part:
`    <build>
        <plugins>
            <plugin>
                <artifactId>maven-clean-plugin</artifactId>
                <version>3.1.0</version>
                <configuration>
                    <failOnError>false</failOnError>
                </configuration>
                <executions>
                    <execution>
                        <id>auto-clean</id>
                        <phase>initialize</phase>
                        <goals>
                            <goal>clean</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-install-plugin</artifactId>
                <version>3.0.0-M1</version>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.1</version>
                <configuration>
                    <suiteXmlFiles>
                        <suiteXmlFile>${xml}</suiteXmlFile>
                    </suiteXmlFiles>
                </configuration>
            </plugin>
        </plugins>
    </build>`
