### ISSUE TITLE
How to generate Selenium log of the executed test?

### ISSUE THREAD

**Issue by aquddos123** [Ardesco/Selenium-Maven-Template#16]
Hi,

I'm exploring this code and have a question. How do we generate Selenium log when we invoke/instantiate WebDriver like in your code? 

I know we can use command line switched (for IE) like --log-file=<logFile> and --log-level=<logLevel> while starting stand alone selenium through command line but in your example the WebDriver is just instantiated via code and there is no way we can define the above command line arguments. 

Any help in this regard will be much appreciated.

Thanks.

**Comment by Ardesco** [comment]
You will want to look at:

https://github.com/Ardesco/Selenium-Maven-Template/blob/master/src/test/java/com/lazerycode/selenium/config/DriverType.java

Here you will be able to tweak the desired capabilities for the driver.  Taking logFile and logLevel for the IE driver as an example:

```java
    IE {
        public DesiredCapabilities getDesiredCapabilities(Proxy proxySettings) {
            DesiredCapabilities capabilities = DesiredCapabilities.internetExplorer();
            capabilities.setCapability(CapabilityType.ForSeleniumServer.ENSURING_CLEAN_SESSION, true);
            capabilities.setCapability(InternetExplorerDriver.ENABLE_PERSISTENT_HOVERING, true);
            capabilities.setCapability("requireWindowFocus", true);
            capabilities.setCapability("logFile", "<logFileLocation>");
            capabilities.setCapability("logLevel", "DEBUG");
            return addProxySettings(capabilities, proxySettings);
        }

        public WebDriver getWebDriverObject(DesiredCapabilities capabilities) {
            return new InternetExplorerDriver(capabilities);
        }
    },
```

For more information on desired capabilities have a look at: 

https://code.google.com/p/selenium/wiki/DesiredCapabilities

Each driver will have its own set of available capabilities, so while logLevel will work with IE there is no guarantee it will work with all other drivers.

**Comment by aquddos123** [comment]
Thanks Asdesco for your help. This worked for me.

**Comment by Ardesco** [comment]
Glad to help :)
