### ISSUE TITLE
Problem with running more than one test

### ISSUE THREAD

**Issue by dmikof** [Ardesco/Selenium-Maven-Template#17]
Hello Mark,
Thanks a lot for this template (and for "Mastering Selenium" book :+1: ). I keep getting "org.openqa.selenium.remote.UnreachableBrowserException" or "org.openqa.selenium.remote.SessionNotFoundException" whenever I try to run more than one test with "-Dthreads=2". Have you ran into such an issue? 
P.S. I was following your book code up to page objects chapter and came here to check possible difference in code (here it may be updated). My code seem to be the same when it matters (I left Chrome, FireFox and Safari on OSX in DriverType class)

**Comment by dmikof** [comment]
Commented out closeDriverObjects() method in DriverFactory and added:  
      @AfterMethod
      public void closeDriver() throws Exception {
      getDriver().quit();
Multiple tests are running ok now, but proper threads handling is of course gone :(

**Comment by dmikof** [comment]
It was caused by my error in code :)

**Comment by Ardesco** [comment]
Glad you sorted it out, would be useful to know what you did so that others who make the same mistake know how to fix it.

**Comment by dmikof** [comment]
Had "@After method" annotation instead of "@After suite" one in closeDriverObjects() method

**Comment by Ardesco** [comment]
Ah, useful to know :)
