### ISSUE TITLE
No directory created for failed test screen shots

### ISSUE THREAD

**Issue by moha297** [Ardesco/Selenium-Maven-Template#18]
I changed the pre-defined test to make a test case fail. There is no directory ${project.basedir}/target/screenshots found.

**Comment by Ardesco** [comment]
Can you provide your maven output when you run the failing test (It should print out the location of any screenshots it creates in the console, or show an error if it couldn't).  It would be useful to see your POM as well

**Comment by moha297** [comment]
I figured the issue. It was due to eclipse not refreshing my directory structure. My bad for not digging deeper before logging the issue. Facepalm Moment! :(

Thanks for the attention.

**Comment by Ardesco** [comment]
Glad you got it sorted out :)
