### ISSUE TITLE
Eclipse pom file error

### ISSUE THREAD

**Issue by cgrandsjo** [Ardesco/Selenium-Maven-Template#19]
Hi,

I had to add <pluginManagement></pluginManagement> to the pom file to get rid of an error in Eclipse Mars.1 Release (4.5.1).
The error states: "Plugin execution not covered by lifecycle configuration: com.lazerycode.selenium:driver-binary-downloader-maven-plugin:1.0.7:selenium (execution: default, phase: test-compile)"

You can read more about it here:
http://stackoverflow.com/questions/6352208/how-to-solve-plugin-execution-not-covered-by-lifecycle-
configuration-for-sprin/13733232#13733232

Keep up the good work! :)

Cheers,
Chris

**Comment by Ardesco** [comment]
pluginManagement is used to define a list of plugins in a parent POM.  Then child POMs can call in specific plugins that are defined in the parent with minimal configuration.

Seeing as there are no child POMs in this project it shouldn't really be using a pluginManagement tag.  

It looks like you have come across this Eclipse quirkiness:  https://www.eclipse.org/m2e/documentation/m2e-execution-not-covered.html

**Comment by Ardesco** [comment]
Issue added to selenium standalone server plugin:

https://github.com/Ardesco/selenium-standalone-server-plugin/issues/31

Closing this one off as it's not a Selenium Maven Template bug.
