### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by rmoszczynski** [Ardesco/Selenium-Maven-Template#20]
Hi, I got:

`java.lang.IllegalStateException: The path to the driver executable must be set by the webdriver.chrome.driver system property;`

**Comment by ham1** [comment]
Try setting the system property as described.
E.g. `mvn ... -Dwebdriver.chrome.driver="c:/path/to/chromedriver.exe"`

**Comment by Ardesco** [comment]
@rmoszczynski my best guess is that the repomap.xml has got out of date and you aren't downloading a valid driver binary.  I'll update to the latest versions of everything later today

@ham1 you don't need to do that with this template.  The driver binary downloader plugin downloads the binaries for you and sets the system property.

**Comment by ham1** [comment]
Ah, didn't know about the plugin. Thanks.
