### ISSUE TITLE
failed to download all of the standalone executables

### ISSUE THREAD

**Issue by Jack-Collins** [Ardesco/Selenium-Maven-Template#23]
![image](https://cloud.githubusercontent.com/assets/13108027/17523559/f38c88b8-5e52-11e6-9c61-85d5df1b4c3c.png)

**Comment by Jack-Collins** [comment]
following the instructions in the readme, am I going wrong somewhere?

**Comment by Ardesco** [comment]
Do you have write access to the folder you are trying to save the binaries to?

Can you perform a `mvn clean install -X` and paste the output here?

**Comment by kmelderis** [comment]
[ERROR] Expected file hash : 'eb61e6dc49832a3d60f708a92fa7299c57cad7db'.
[ERROR] Actual file hash   : 'afdedbc0c109a21aafcbb7e8ae15d20e6eb2cd2f'.

**Comment by Ardesco** [comment]
Looks like the phantoms file that's being downloaded is not the expected one.  Can you show my the phantoms block in your RepositoryMap.xml you are using (will depend upon your OS).

**Comment by kmelderis** [comment]
I did a fresh:
git clone
mvn clean verify -Doverwrite.binaries=true

WinOS10


`<driver id="phantomjs">
            <version id="2.1.1">
                <bitrate thirtytwobit="true" sixtyfourbit="true">
                    <filelocation>https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-windows.zip</filelocation>
                    <hash>eb61e6dc49832a3d60f708a92fa7299c57cad7db</hash>
                    <hashtype>sha1</hashtype>
                </bitrate>
            </version>
            <version id="1.9.8">
                <bitrate thirtytwobit="true" sixtyfourbit="true">
                    <filelocation>https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-windows.zip</filelocation>
                    <hash>4531bd64df101a689ac7ac7f3e11bb7e77af8eff</hash>
                    <hashtype>sha1</hashtype>
                </bitrate>
            </version>
        </driver>`

**Comment by Ardesco** [comment]
I've just downloaded the file from that location and performed a hash of it and the file has is `eb61e6dc49832a3d60f708a92fa7299c57cad7db`.  Looks like for some reason you are getting a different file coming down.

**Comment by kmelderis** [comment]
It is strange because I managed to download and test that google test example about 2h ago.

**Comment by Ardesco** [comment]
Really you want to work out why you are getting a different file.

If you are happy that the file coming down works and sin't something dodgy you can update the hash in your RepositoyMap.xml, or you can turn off hash checking in he selenium binary downloader configuration so that it will just download whatever:
```
<checkFileHashes>true</checkFileHashes>
```
 see the config block instruction in the README.md at https://github.com/Ardesco/selenium-standalone-server-plugin for more info.

**Comment by kmelderis** [comment]
I wonder why is there 2 versions of PhantomJS in RepositoryMap.xml ?

**Comment by Ardesco** [comment]
Because one is the 1.9.x version and the other is the 2.1.x version.  You can delete the one you aren't interested in.  2.1.x is the latest but used to have problems with Selenium so you probably wanted to use the 1.9.x branch.

This is just an example RepositoryMap.xml to start you off, you can tweak it as you see fit for your own purposes.  It's easier to give you link to both to start with and then you can choose which one to use.

**Comment by kmelderis** [comment]
Will go along those lines, thanks.

**Comment by Ardesco** [comment]
@Jack-Collins is this issue all good now?

**Comment by Jack-Collins** [comment]
yeah sure, thanks

**Comment by vazl** [comment]
Hi,

I have similar issue, but some of the commands do not work for me, e.g.

c:\Temp\Selenium-Maven-Template-master>mvn clean install -eX
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Selenium Maven Template 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.493 s
[INFO] Finished at: 2016-09-29T16:38:25+10:00
[INFO] Final Memory: 5M/121M
[INFO] ------------------------------------------------------------------------
[ERROR] Unknown lifecycle phase "X". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<g



Am I doing something wrong?

Thanks

**Comment by Ardesco** [comment]
What version of Maven and Java are you on?

The above looks like maven is getting confused somewhere.  Have you modified anything?

**Comment by vazl** [comment]
Java version: 1.8
Maven version: 3.3.3

I did not modify anything
