### ISSUE TITLE
Chrome configuration works, but not Firefox

### ISSUE THREAD

**Issue by heatherita** [Ardesco/Selenium-Maven-Template#24]
Hello.

This looks like it will be a very useful package. Thank you for providing it!

My experience is that Chrome seems to work but Firefox does not, on my system (AMD 54 Linux).

**Here is the Chrome output:**

```
cd /home/hpropes/NetBeansProjects/Selenium-Maven-Template-master; JAVA_HOME=/usr/local/java/jdk1.8.0_60 /home/hpropes/netbeans-8.0.2/java/maven/bin/mvn -Dbrowser=chrome -Pselenium-tests install
Scanning for projects...
                                                                        
------------------------------------------------------------------------
Building Selenium Maven Template 1.0-SNAPSHOT
------------------------------------------------------------------------

--- maven-resources-plugin:2.5:resources (default-resources) @ maven-template ---
[debug] execute contextualize
Using 'UTF-8' encoding to copy filtered resources.
skip non existing resourceDirectory /home/hpropes/NetBeansProjects/Selenium-Maven-Template-master/src/main/resources

--- maven-compiler-plugin:3.5.1:compile (default-compile) @ maven-template ---
No sources to compile

--- maven-resources-plugin:2.5:testResources (default-testResources) @ maven-template ---
[debug] execute contextualize
Using 'UTF-8' encoding to copy filtered resources.
Copying 9 resources

--- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ maven-template ---
Nothing to compile - all classes are up to date

>>> driver-binary-downloader-maven-plugin:1.0.11:selenium (default) @ maven-template >>>

--- maven-resources-plugin:2.5:resources (default-resources) @ maven-template ---
[debug] execute contextualize
Using 'UTF-8' encoding to copy filtered resources.
skip non existing resourceDirectory /home/hpropes/NetBeansProjects/Selenium-Maven-Template-master/src/main/resources

--- maven-compiler-plugin:3.5.1:compile (default-compile) @ maven-template ---
No sources to compile

--- maven-resources-plugin:2.5:testResources (default-testResources) @ maven-template ---
[debug] execute contextualize
Using 'UTF-8' encoding to copy filtered resources.
Copying 9 resources

--- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ maven-template ---
Nothing to compile - all classes are up to date

<<< driver-binary-downloader-maven-plugin:1.0.11:selenium (default) @ maven-template <<<

--- driver-binary-downloader-maven-plugin:1.0.11:selenium (default) @ maven-template ---
 
--------------------------------------------------------
 DOWNLOADING SELENIUM STAND-ALONE EXECUTABLE BINARIES...
--------------------------------------------------------
 
 file:/home/hpropes/NetBeansProjects/Selenium-Maven-Template-master/src/test/resources/RepositoryMap.xml is valid
 
Only get drivers for current Operating System: true
Getting drivers for current operating system only.
Archives will be downloaded to '/home/hpropes/NetBeansProjects/Selenium-Maven-Template-master/src/test/resources/selenium_standalone_zips'
Standalone executable files will be extracted to '/home/hpropes/NetBeansProjects/Selenium-Maven-Template-master/src/test/resources/selenium_standalone_binaries'
 
Preparing to download Selenium Standalone Executable Binaries...
Binary 'geckodriver' Exists: true
Using existing 'geckodriver'binary.
Binary 'operadriver' Exists: true
Using existing 'operadriver'binary.
Binary 'chromedriver' Exists: true
Using existing 'chromedriver'binary.
Binary 'phantomjs' Exists: true
Using existing 'phantomjs'binary.
Setting maven property - ${webdriver.gecko.driver} = /home/hpropes/NetBeansProjects/Selenium-Maven-Template-master/src/test/resources/selenium_standalone_binaries/linux/marionette/64bit/geckodriver
Setting maven property - ${webdriver.opera.driver} = /home/hpropes/NetBeansProjects/Selenium-Maven-Template-master/src/test/resources/selenium_standalone_binaries/linux/operachromium/64bit/operadriver
Setting maven property - ${webdriver.chrome.driver} = /home/hpropes/NetBeansProjects/Selenium-Maven-Template-master/src/test/resources/selenium_standalone_binaries/linux/googlechrome/64bit/chromedriver
Setting maven property - ${phantomjs.binary.path} = /home/hpropes/NetBeansProjects/Selenium-Maven-Template-master/src/test/resources/selenium_standalone_binaries/linux/phantomjs/64bit/phantomjs
 
--------------------------------------------------------
SELENIUM STAND-ALONE EXECUTABLE DOWNLOADS COMPLETE
--------------------------------------------------------
 

--- maven-surefire-plugin:2.10:test (default-test) @ maven-template ---
Surefire report directory: /home/hpropes/NetBeansProjects/Selenium-Maven-Template-master/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0


--- maven-jar-plugin:2.3.2:jar (default-jar) @ maven-template ---
Building jar: /home/hpropes/NetBeansProjects/Selenium-Maven-Template-master/target/maven-template-1.0-SNAPSHOT.jar

--- maven-failsafe-plugin:2.19.1:integration-test (default) @ maven-template ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.lazerycode.selenium.tests.GoogleExampleIT
 
Current Operating System: LINUX
Current Architecture: amd64
Current Browser Selection: CHROME
 
Starting ChromeDriver 2.23.409687 (c46e862757edc04c06b1bd88724d15a5807b84d1) on port 2856
Only local connections are allowed.
Page title is: Google
Page title is: Cheese! - Google Search
Page title is: Google
Page title is: Milk! - Google Search
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.327 sec - in com.lazerycode.selenium.tests.GoogleExampleIT

Results :

Tests run: 2, Failures: 0, Errors: 0, Skipped: 0


--- maven-failsafe-plugin:2.19.1:verify (default) @ maven-template ---

--- maven-install-plugin:2.3.1:install (default-install) @ maven-template ---
Installing /home/hpropes/NetBeansProjects/Selenium-Maven-Template-master/target/maven-template-1.0-SNAPSHOT.jar to /home/hpropes/.m2/repository/com/lazerycode/selenium/maven-template/1.0-SNAPSHOT/maven-template-1.0-SNAPSHOT.jar
Installing /home/hpropes/NetBeansProjects/Selenium-Maven-Template-master/pom.xml to /home/hpropes/.m2/repository/com/lazerycode/selenium/maven-template/1.0-SNAPSHOT/maven-template-1.0-SNAPSHOT.pom
------------------------------------------------------------------------
BUILD SUCCESS
------------------------------------------------------------------------
Total time: 7.489s
Finished at: Mon Aug 15 09:36:02 EDT 2016
Final Memory: 18M/468M
------------------------------------------------------------------------
The requested profile "skinny-war" could not be activated because it does not exist.
The requested profile "ejb-devel" could not be activated because it does not exist.

```

**Comment by heatherita** [comment]
**And here is the firefox output:**

cd /home/hpropes/NetBeansProjects/Selenium-Maven-Template-master; JAVA_HOME=/usr/local/java/jdk1.8.0_60 /home/hpropes/netbeans-8.0.2/java/maven/bin/mvn -Dbrowser=firefox -Pselenium-tests install
Scanning for projects...
                                                                        
------------------------------------------------------------------------
Building Selenium Maven Template 1.0-SNAPSHOT
------------------------------------------------------------------------

--- maven-resources-plugin:2.5:resources (default-resources) @ maven-template ---
[debug] execute contextualize
Using 'UTF-8' encoding to copy filtered resources.
skip non existing resourceDirectory /home/hpropes/NetBeansProjects/Selenium-Maven-Template-master/src/main/resources

--- maven-compiler-plugin:3.5.1:compile (default-compile) @ maven-template ---
No sources to compile

--- maven-resources-plugin:2.5:testResources (default-testResources) @ maven-template ---
[debug] execute contextualize
Using 'UTF-8' encoding to copy filtered resources.
Copying 9 resources

--- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ maven-template ---
Nothing to compile - all classes are up to date

>>> driver-binary-downloader-maven-plugin:1.0.11:selenium (default) @ maven-template >>>

--- maven-resources-plugin:2.5:resources (default-resources) @ maven-template ---
[debug] execute contextualize
Using 'UTF-8' encoding to copy filtered resources.
skip non existing resourceDirectory /home/hpropes/NetBeansProjects/Selenium-Maven-Template-master/src/main/resources

--- maven-compiler-plugin:3.5.1:compile (default-compile) @ maven-template ---
No sources to compile

--- maven-resources-plugin:2.5:testResources (default-testResources) @ maven-template ---
[debug] execute contextualize
Using 'UTF-8' encoding to copy filtered resources.
Copying 9 resources

--- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ maven-template ---
Nothing to compile - all classes are up to date

<<< driver-binary-downloader-maven-plugin:1.0.11:selenium (default) @ maven-template <<<

--- driver-binary-downloader-maven-plugin:1.0.11:selenium (default) @ maven-template ---
 
--------------------------------------------------------
 DOWNLOADING SELENIUM STAND-ALONE EXECUTABLE BINARIES...
--------------------------------------------------------
 
 file:/home/hpropes/NetBeansProjects/Selenium-Maven-Template-master/src/test/resources/RepositoryMap.xml is valid
 
Only get drivers for current Operating System: true
Getting drivers for current operating system only.
Archives will be downloaded to '/home/hpropes/NetBeansProjects/Selenium-Maven-Template-master/src/test/resources/selenium_standalone_zips'
Standalone executable files will be extracted to '/home/hpropes/NetBeansProjects/Selenium-Maven-Template-master/src/test/resources/selenium_standalone_binaries'
 
Preparing to download Selenium Standalone Executable Binaries...
Binary 'geckodriver' Exists: true
Using existing 'geckodriver'binary.
Binary 'operadriver' Exists: true
Using existing 'operadriver'binary.
Binary 'chromedriver' Exists: true
Using existing 'chromedriver'binary.
Binary 'phantomjs' Exists: true
Using existing 'phantomjs'binary.
Setting maven property - ${webdriver.gecko.driver} = /home/hpropes/NetBeansProjects/Selenium-Maven-Template-master/src/test/resources/selenium_standalone_binaries/linux/marionette/64bit/geckodriver
Setting maven property - ${webdriver.opera.driver} = /home/hpropes/NetBeansProjects/Selenium-Maven-Template-master/src/test/resources/selenium_standalone_binaries/linux/operachromium/64bit/operadriver
Setting maven property - ${webdriver.chrome.driver} = /home/hpropes/NetBeansProjects/Selenium-Maven-Template-master/src/test/resources/selenium_standalone_binaries/linux/googlechrome/64bit/chromedriver
Setting maven property - ${phantomjs.binary.path} = /home/hpropes/NetBeansProjects/Selenium-Maven-Template-master/src/test/resources/selenium_standalone_binaries/linux/phantomjs/64bit/phantomjs
 
--------------------------------------------------------
SELENIUM STAND-ALONE EXECUTABLE DOWNLOADS COMPLETE
--------------------------------------------------------
 

--- maven-surefire-plugin:2.10:test (default-test) @ maven-template ---
Surefire report directory: /home/hpropes/NetBeansProjects/Selenium-Maven-Template-master/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0


--- maven-jar-plugin:2.3.2:jar (default-jar) @ maven-template ---
Building jar: /home/hpropes/NetBeansProjects/Selenium-Maven-Template-master/target/maven-template-1.0-SNAPSHOT.jar

--- maven-failsafe-plugin:2.19.1:integration-test (default) @ maven-template ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.lazerycode.selenium.tests.GoogleExampleIT
 
Current Operating System: LINUX
Current Architecture: amd64
Current Browser Selection: FIREFOX
 
 
Current Operating System: LINUX
Current Architecture: amd64
Current Browser Selection: FIREFOX
 
Unable to capture screenshot...
java.lang.IllegalStateException: The driver executable does not exist: /home/hpropes/NetBeansProjects/Selenium-Maven-Template-master
	at com.google.common.base.Preconditions.checkState(Preconditions.java:199)
	at org.openqa.selenium.remote.service.DriverService.checkExecutable(DriverService.java:121)
	at org.openqa.selenium.remote.service.DriverService.findExecutable(DriverService.java:116)
	at org.openqa.selenium.firefox.GeckoDriverService.access$100(GeckoDriverService.java:38)
	at org.openqa.selenium.firefox.GeckoDriverService$Builder.findDefaultExecutable(GeckoDriverService.java:91)
	at org.openqa.selenium.remote.service.DriverService$Builder.build(DriverService.java:296)
	at org.openqa.selenium.firefox.FirefoxDriver.createCommandExecutor(FirefoxDriver.java:245)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:220)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:215)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:132)
	at com.lazerycode.selenium.config.DriverType$1.getWebDriverObject(DriverType.java:32)
	at com.lazerycode.selenium.config.DriverFactory.instantiateWebDriver(DriverFactory.java:88)
	at com.lazerycode.selenium.config.DriverFactory.getDriver(DriverFactory.java:42)
	at com.lazerycode.selenium.DriverBase.getDriver(DriverBase.java:34)
	at com.lazerycode.selenium.listeners.ScreenshotListener.onTestFailure(ScreenshotListener.java:51)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1691)
	at org.testng.internal.Invoker.runTestListeners(Invoker.java:1675)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:700)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
 
Current Operating System: LINUX
Current Architecture: amd64
Current Browser Selection: FIREFOX
 
 
Current Operating System: LINUX
Current Architecture: amd64
Current Browser Selection: FIREFOX
 
Tests run: 4, Failures: 3, Errors: 0, Skipped: 1, Time elapsed: 0.247 sec <<< FAILURE! - in com.lazerycode.selenium.tests.GoogleExampleIT
googleCheeseExample(com.lazerycode.selenium.tests.GoogleExampleIT)  Time elapsed: 0.072 sec  <<< FAILURE!
java.lang.IllegalStateException: The driver executable does not exist: /home/hpropes/NetBeansProjects/Selenium-Maven-Template-master
	at com.lazerycode.selenium.tests.GoogleExampleIT.googleCheeseExample(GoogleExampleIT.java:18)

clearCookies(com.lazerycode.selenium.tests.GoogleExampleIT)  Time elapsed: 0.074 sec  <<< FAILURE!
java.lang.IllegalStateException: The driver executable does not exist: /home/hpropes/NetBeansProjects/Selenium-Maven-Template-master

clearCookies(com.lazerycode.selenium.tests.GoogleExampleIT)  Time elapsed: 0.003 sec  <<< FAILURE!
java.lang.IllegalStateException: The driver executable does not exist: /home/hpropes/NetBeansProjects/Selenium-Maven-Template-master


Results :

Failed tests: 
com.lazerycode.selenium.tests.GoogleExampleIT.clearCookies(com.lazerycode.selenium.tests.GoogleExampleIT)
  Run 1: GoogleExampleIT>DriverBase.clearCookies:39->DriverBase.getDriver:34 » IllegalState
  Run 2: GoogleExampleIT>DriverBase.clearCookies:39->DriverBase.getDriver:34 » IllegalState

  GoogleExampleIT.googleCheeseExample:18->DriverBase.getDriver:34 » IllegalState

Tests run: 3, Failures: 2, Errors: 0, Skipped: 1


--- maven-failsafe-plugin:2.19.1:verify (default) @ maven-template ---
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 2.294s
Finished at: Mon Aug 15 09:39:19 EDT 2016
Final Memory: 18M/488M
------------------------------------------------------------------------
The requested profile "skinny-war" could not be activated because it does not exist.
The requested profile "ejb-devel" could not be activated because it does not exist.
Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.19.1:verify (default) on project maven-template: There are test failures.

Please refer to /home/hpropes/NetBeansProjects/Selenium-Maven-Template-master/target/failsafe-reports for the individual test results.
-> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException


Please let me know if you need additional info.

thanks!

Heather

**Comment by Ardesco** [comment]
Can you show me what is in the directory

```
home/hpropes/NetBeansProjects/Selenium-Maven-Template-master/src/test/resources/selenium_standalone_binaries/linux/marionette/64bit/
```

It looks like it can't find the executable for some reason

**Comment by heatherita** [comment]
In there is a binary file called geckodriver.

**Comment by Ardesco** [comment]
Should be fixed now, it was a stupid typo.

**Comment by heatherita** [comment]
thank you!
