### ISSUE TITLE
maximise() fails in docker container with errorjava.awt.HeadlessException 

### ISSUE THREAD

**Issue by vikramvi** [Ardesco/Selenium-Maven-Template#29]
Hi @Ardesco 

I've found your solution about browser maximize in https://groups.google.com/forum/#!msg/webdriver/9Ma5IfB_kzk/-vdhBhkPHs4J

But it fails in case of container setup on mac mini , any idea what may be going wrong ?

It works perfectly with stand alone browser through

public void maximise() {
            Toolkit toolkit = Toolkit.getDefaultToolkit();
            Dimension screenResolution = new Dimension((int) toolkit.getScreenSize().getWidth(), (int) toolkit.getScreenSize().getHeight());
            driver.manage().window().setSize(screenResolution);
}

java.awt.HeadlessException      at sun.awt.HeadlessToolkit.getScreenSize(HeadlessToolkit.java:284)   

Thanks & Regards,
Vikram

**Comment by Ardesco** [comment]
Closing this as it's nothing to do with the template.

as noted in the link above:

> The suggestion below is locked to windows specifically and if ported across to Linux you would need to detect which desktop environment you are running, I’m sure the commands in KDE, Gnome and LXDE are different (different versions of KDE and Gnome probably do it differently as well as they have evolved).  If you are testing cross platform with various linux builds I can see the below becoming a maintenance nightmare.

Also you are looking at something posted 5 years ago, If you want to maximise the browser use the built in selenium function:

```driver.manage().window().maximize();```
