### ISSUE TITLE
pom does not build as it is

### ISSUE THREAD

**Issue by jackrabb1t** [Ardesco/Selenium-Maven-Template#32]
i am running on windows 7 / jdk 7 /maven 3.0.4

selenium version 3.0.0 does not play well with jdk 7

Moving the version to 2.47.1 works to get the builds going.

**Comment by Ardesco** [comment]
Selenium 3.x requires Java 8, also Java 7 is officially end of life (https://java.com/en/download/faq/java_7.xml).  

If you are starting up a new project now, you really should not be using Java 7, you should be using Java 8.

**Comment by jackrabb1t** [comment]
yes, i was just pointing out that the pom is inconsistent.
the maven-compiler-plugin points to 1.7 while the selenium is at 3.0.0
that's all.

**Comment by Ardesco** [comment]
OK, that's not what you said in the initial issue you raised :)
