### ISSUE TITLE
cucumber-jvm support

### ISSUE THREAD

**Issue by gkexplore** [Ardesco/Selenium-Maven-Template#35]
Team,
 is there any plan to add cucumber-jvm to this project as it supports BDD?.

Thanks
Karthik

**Comment by Ardesco** [comment]
BDD is all about conversations with the business to find out what the users really want to have built for them; it's not about the tech stack that you use:

https://lizkeogh.com/2015/03/27/what-is-bdd/

This template will allow you to get quickly up and running when it comes to writing automated tests, which can be very useful as part of your BDD journey.  

I prefer the use of good page objects and clear code that is easy for nontechnical people to follow.  You would be surprised how easy well written code, with well written variable names, and complexity abstracted into sensibly named functions is to read.

I'm personally not a fan of Cucumber, it's another layer of abstraction that in my mind you don't need.  I prefer easy to read code over test that have been mangled into a Given When Then structure when it doesn't always make sense for them to be in that structure (Have you ever seen things like _"Given I have serenity running, When i run a browser test, Then the browser test should pass"_) 

This template will not be adding Cucumber into it (and it won't force you to write your tests using the Gherkin language syntax), but you can add it in yourself if you see value in that. Be warned, Cucumber is not thread safe so you will need to spin up each instance of Cucumber in a separate JVM.  Also be warned that step def files can easily get out of hand and end up being thousands of lines long with duplicate definitions for similar functionality littered all over the place.

Good luck.

**Comment by gkexplore** [comment]
Thank you for the explanation
