### ISSUE TITLE
Question: hub/grid and remote connection 

### ISSUE THREAD

**Issue by jauyzed** [Ardesco/Selenium-Maven-Template#36]
Hello Ardesco, 

This is a great template and has helped me to set up the selenium tests locally. I would like to run the tests on hub/grid setup with the same template. Im trying to integrate this with our current CI process. I have windows machine in the network which acts as a hub and grid with all the popular browsers installed. jenkins box doesn't have display property as it is a EC2 instance and so is the windows.   

I will be running the tests code as a jenkins job. The job has a script running which basically connects to the hub/grid setup. 

mvn clean verify -DseleniumGridURL=http://jenkins:*******@selenium-hub.blah.com:80/wd/hub

Is that about right?  

Thanks!

**Comment by Ardesco** [comment]
You'll also need to add `-Dremote=true`

so:

```
mvn clean verify -DseleniumGridURL=http://jenkins:*******@selenium-hub.blah.com:80/wd/hub -Dremote=true
```

**Comment by jauyzed** [comment]
The command worked

`mvn clean verify -DseleniumGridURL=http://jenkins:*******@<ipaddr>:80/wd/hub -Dremote=true`

org.openqa.selenium.SessionNotCreatedException: 
Unable to create new remote session. desired capabilities = Capabilities [{marionette=true, browserName=firefox, version=, platform=ANY}], required capabilities = Capabilities [{}]

The remote machine does have ff browser installed. Do I need to have geckodriver in the remote machine? If so where should I place it, PATH?

What am i doing wrong? 

Thanks!

**Comment by Ardesco** [comment]
Sounds like a grid setup problem, it depends what version of selenium you are running on the grid and what browsers the grid is exposing as available.

You should be able to navigate to the grid hub in a browser and it will show you what remote instances are available.

**Comment by jauyzed** [comment]
The setup seems to be working on windows where the tests need to be performed. same machine is acting as HUB and GRID 

HUB:
`java -jar selenium-server-standalone-3.1.0.jar -role hub -host <machine ipadd> -port 4444`

GRID:
`java -jar selenium-server-standalone-3.1.0.jar -role node -port 5555 -hub http://127.0.0.1:4444/grid/register -browser "browserName=firefox,platform=WINDOWS" -browser "browserName=opera,platform=WINDOWS" -browser "browserName=safari,platform=WINDOWS" -browser "browserName=internet explorer,platform=WINDOWS" -browser "browserName=chrome,platform=WINDOWS"`

running that gave the following output:
`16:26:38.634 INFO - Selenium build info: version: '3.1.0', revision: '86a5d70'
16:26:38.635 INFO - Launching a Selenium Grid node
2017-04-19 16:26:39.006:INFO::main: Logging initialized @609ms
16:26:39.037 INFO - Driver class not found: com.opera.core.systems.OperaDriver
16:26:39.037 INFO - Driver provider com.opera.core.systems.OperaDriver registration is skipped:
Unable to create new instances on this machine.
16:26:39.038 INFO - Driver class not found: com.opera.core.systems.OperaDriver
16:26:39.038 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
16:26:39.040 INFO - Driver provider org.openqa.selenium.safari.SafariDriver registration is skipped:
 registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform XP
2017-04-19 16:26:39.067:INFO:osjs.Server:main: jetty-9.2.15.v20160210
2017-04-19 16:26:39.083:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@5223e5ee{/,null,AVAILABLE}
2017-04-19 16:26:39.097:INFO:osjs.ServerConnector:main: Started ServerConnector@2e4b8173{HTTP/1.1}{0.0.0.0:5555}
2017-04-19 16:26:39.098:INFO:osjs.Server:main: Started @701ms
16:26:39.098 INFO - Selenium Grid node is up and ready to register to the hub
16:26:39.109 INFO - Starting auto registration thread. Will try to register every 5000 ms.
16:26:39.109 INFO - Registering the node to the hub: http://127.0.0.1:4444/grid/register
16:27:41.585 INFO - The node is registered to the hub and ready to use
16:27:46.701 INFO - SessionCleaner initialized with insideBrowserTimeout 0 and clientGoneTimeout 1800000 polling every 180000`

Im not providing "max instances" currently until I get this to work. 

On the browser i see all browser instances hitting the external IP: 

browserTimeout: 0
debug: false
help: false
port: 5555
role: node
timeout: 1800
cleanUpCycle: 5000
host: <ip addr>
maxSession: 5
capabilities: Capabilities [{seleniumProtocol=WebDriver, browserName=firefox, platform=WINDOWS}]
capabilities: Capabilities [{seleniumProtocol=WebDriver, browserName=opera, platform=WINDOWS}]
capabilities: Capabilities [{seleniumProtocol=WebDriver, browserName=safari, platform=WINDOWS}]
capabilities: Capabilities [{seleniumProtocol=WebDriver, browserName=internet explorer, platform=WINDOWS}]
capabilities: Capabilities [{seleniumProtocol=WebDriver, browserName=chrome, platform=WINDOWS}]
downPollingLimit: 2
hub: http://127.0.0.1:4444/grid/register
id: http://172.31.23.17:5555
hubHost: 127.0.0.1
hubPort: 4444
nodePolling: 5000
nodeStatusCheckTimeout: 5000
proxy: org.openqa.grid.selenium.proxy.DefaultRemoteProxy
register: true
registerCycle: 5000
remoteHost: http://172.31.23.17:5555
unregisterIfStillDownAfter: 60000

![screen shot 2017-04-19 at 10 42 37 am](https://cloud.githubusercontent.com/assets/18094384/25194108/9970917e-24f6-11e7-923b-6f532da7bff1.png)

Error on the console:
org.openqa.selenium.SessionNotCreatedException: 
Unable to create new remote session. desired capabilities = Capabilities [{marionette=true, browserName=firefox, version=, platform=ANY}], required capabilities = Capabilities [{}]
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:49:13 -0700'

**Comment by jauyzed** [comment]
Can't get it to work even after adding `geckodriver.exe` to the path and also tried running it with absolute path:  
`java -Dwebdriver.gecko.driver=C:\selenium_grid\geckodriver\geckodriver.exe -jar selenium-server-standalone-3.1.0.jar -role hub -host <machineip> -port 4444`

The hub and grid registers and works fine. I have posted the setup in my previous post ^. 

What else am I missing?

**Comment by jauyzed** [comment]
resolved! was a networking issue between machines
