### ISSUE TITLE
problems with file permissions

### ISSUE THREAD

**Issue by Joel-Costamagna** [Ardesco/Selenium-Maven-Template#37]
when I use -Doverwritefile=true, the downloaded drivers does not have the executable permission.

I need to manually connect to my server and chmod the files to make it work.
How can I change the permission directly in the project config ?

**Comment by Ardesco** [comment]
hmm it should be making them executable:

https://github.com/Ardesco/selenium-standalone-server-plugin/blob/master/src/main/java/com/lazerycode/selenium/extract/FileExtractor.java#L167

Are you seeing anything logged saying it couldn't set the executable flag?

**Comment by Joel-Costamagna** [comment]
There was nothing anormal in the logs, but I restarted the server and it works now, so I think it was a system error.
