### ISSUE TITLE
IEDriverServer in 32/64 bit

### ISSUE THREAD

**Issue by paddyez** [Ardesco/Selenium-Maven-Template#40]
I did not find a way in the README.md to start a specific bit version of the Server. But I read that it is best practice to use the 32 bit version. It seems to be the default setting in this project the 64 bit version is used.

**Comment by Ardesco** [comment]
you could tweak the repository map.xml and set the following:

```
<driver id="internetexplorer">
            <version id="3.7.0">
                <bitrate thirtytwobit="true" sixtyfourbit="true">
                    <filelocation>http://selenium-release.storage.googleapis.com/3.7/IEDriverServer_Win32_3.7.0.zip</filelocation>
                    <hash>ded0a82cab46538751ba17206f55c112674585d6</hash>
                    <hashtype>sha1</hashtype>
                </bitrate>
            </version>
        </driver>
```

The driver binary downloader will set up the system properties based upon your repository map.xml configuration.

**Comment by paddyez** [comment]
The final solution was replacing the repository map with https://gist.github.com/Ardesco/ccad4f10ed15daefaea5a086e4a30296

After that "mvn clean verify -Doverwrite.binaries=true" and the 32 bit IE server driver will start.
