### ISSUE TITLE
driver is not executable

### ISSUE THREAD

**Issue by stefanchiriac** [Ardesco/Selenium-Maven-Template#44]
Hello,

I'm trying to run tests from Jenkins on a ubuntu 16.04 server and I'm getting the following error.
I tried to set it manually from server, but seems like on the next run the permissions are overwritten. I also tried to make it executable programmatically on DriverBase > instantiateDriverObject() and still the same.
There is any way to fix this?

Thanks

```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running TestSuite
Feb 21, 2018 11:13:20 AM org.openqa.selenium.remote.DesiredCapabilities chrome
INFO: Using new ChromeOptions() is preferred to DesiredCapabilities.chrome()
 
Current Operating System: LINUX
Current Architecture: amd64
Current Browser Selection: CHROME_HEADLESS
 
====== Going to use LOCAL ======
Feb 21, 2018 11:13:20 AM org.openqa.selenium.remote.DesiredCapabilities chrome
INFO: Using new ChromeOptions() is preferred to DesiredCapabilities.chrome()
 
Current Operating System: LINUX
Current Architecture: amd64
Current Browser Selection: CHROME_HEADLESS
 
====== Going to use LOCAL ======
Unable to capture screenshot...
java.lang.IllegalStateException: The driver is not executable: /path/to/project/src/test/resources/selenium_standalone_binaries/linux/googlechrome/64bit/chromedriver
```

**Comment by Ardesco** [comment]
We already try to make the file executable when it is downloaded:

https://github.com/Ardesco/selenium-standalone-server-plugin/blob/e2021cd95267570046985df5cba76169689e2edc/src/main/java/com/lazerycode/selenium/extract/FileExtractor.java#L168

Sounds like you have some process that is switching it back, or builds are running as a user who doesn't have permissions to make files executable

**Comment by stefanchiriac** [comment]
I ran it with `-Doverwrite.binaries=true` and seems to be working now

**Comment by stefanchiriac** [comment]
is doing anything different when I run with -Doverwrite.binaries=true?
downloading the binaries all the time when I run the tests doesn't feel right

**Comment by Ardesco** [comment]
When you overwrite the binaries it effectively deletes the old one, and then writes a new one and sets the file as executable again.  The problem you have, is that something is modifying the permissions on the file between runs.

**Comment by Ardesco** [comment]
Closing as there doesn't seem to be anything else to do right now.
