### ISSUE TITLE
FirefoxOptions does not have any effect

### ISSUE THREAD

**Issue by to-mats** [Ardesco/Selenium-Maven-Template#47]
Hello,

First of all - thank you very much for your excellent book and the code you share with us.

I think there is an issue with your DriverType.java code. You have the following code there:
    
```
    FIREFOX {
        public MutableCapabilities getDesiredCapabilities(Proxy proxySettings) {
            FirefoxOptions firefoxOptions = new FirefoxOptions();
            firefoxOptions.addPreference("marionette", true);
            return addProxySettings(firefoxOptions, proxySettings);
        }

        public RemoteWebDriver getWebDriverObject(MutableCapabilities capabilities) {
            return new FirefoxDriver(capabilities);
        }
    },
```
    

The following line does not have any effect:

`firefoxOptions.addPreference("marionette", true);
`

If needed, it should be:

`firefoxOptions.setCapability("marionette", true);
`

Second - in order to use FirefoxOptions in getDesiredCapabilities so that they have effect, I have changed the getWebDriverObject method from:
```
        public RemoteWebDriver getWebDriverObject(MutableCapabilities capabilities) {
        	return new FirefoxDriver(capabilities);
        }
```
to:
```
        public RemoteWebDriver getWebDriverObject(MutableCapabilities capabilities) {
        	return new FirefoxDriver((FirefoxOptions) capabilities);
        }
```
        
When is it useful? In your book you have an example with JMeter. In order to use it with Firefox without "Content encoding error", I added the following Firefox option:

`firefoxOptions.addPreference("network.http.accept-encoding.secure", "true");
`

and optional (not needed for your Google example):

`firefoxOptions.addPreference("network.http.accept-encoding", "true");
`

But they had no effect in your code until I changed it the way I showed above.

**Comment by Ardesco** [comment]
There have been some changes in the latest versions of Selenium so this is now a bit out of date.  I'm currently working on the 2nd Edition of the book and getting stuff up to date, this repo will be updated soon as well (not enough hours in the day at the moment)

**Comment by Ardesco** [comment]
This should be fixed now.
