### ISSUE TITLE
Case with test execution

### ISSUE THREAD

**Issue by JivkoKostadinov** [Ardesco/Selenium-Maven-Template#49]
Hi. Can you check, why I change  GoogleExampleIT.java  to TestExample.java, or any random string maven failed to execute test class?

Thanks.

**Comment by Ardesco** [comment]
Because that's the way the maven-failsafe-plugin works:

http://maven.apache.org/surefire/maven-failsafe-plugin/examples/inclusion-exclusion.html

It expects to see IT in the name

**Comment by JivkoKostadinov** [comment]
Great. Thanks for the support.
