### ISSUE TITLE
Java file name ending with Test fails to execute

### ISSUE THREAD

**Issue by SreecharanShroff** [Ardesco/Selenium-Maven-Template#50]
src/test/java/com.lazerycode.selenium.tests has GETest.java
upon "mvn clean verify", tests fail to execute, logs enclosed GETest.chrome.log

works fine when GETest.java is renamed to GEIT.java
[GETest.chrome.log](https://github.com/Ardesco/Selenium-Maven-Template/files/2182435/GETest.chrome.log)

**Comment by Ardesco** [comment]
Make sure the name ends with IT.  This template uses the maven-failsafe-plugin to execute integration tests:

https://maven.apache.org/surefire/maven-failsafe-plugin/

As a result it searches for tests using the failsafe rules, not the surefire rules (surefire is for unit tests, not integration tests)

https://maven.apache.org/surefire/maven-failsafe-plugin/examples/inclusion-exclusion.html
