### ISSUE TITLE
How can we generate separate log file for each test?

### ISSUE THREAD

**Issue by SawantR** [Ardesco/Selenium-Maven-Template#56]
I want to generate separate log file for each test executed? How can we implement it?

**Comment by Ardesco** [comment]
You could do something like this:

https://stackoverflow.com/questions/46640824/configuring-logback-xml-to-output-all-log-messages-in-one-file-or-in-separate-fi

**Comment by Ardesco** [comment]
I'm going to assume this is fixed and mark it as closed.
