### ISSUE TITLE
Where to download com.lazerycode.selenium:query:jar:2.0.0-beta3 

### ISSUE THREAD

**Issue by onlonely** [Ardesco/Selenium-Maven-Template#57]
[ERROR] Failed to execute goal on project maven-template: Could not resolve dependencies for project com.lazerycode.selenium:maven-template:jar:1.0-SNAPSHOT: Failure to find com.lazerycode.selenium:query:jar:2.0.0-beta3 in https://oss.sonatype.org/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of nexus has elapsed or updates are forced -> [Help 1]

I can't download from you nexus.

**Comment by yelouardi** [comment]
any response ?

**Comment by onlonely** [comment]
ok
