### ISSUE TITLE
Failed to execute goal net.wouterdanes.docker... Connection refused

### ISSUE THREAD

**Issue by adityai** [Ardesco/Selenium-Maven-Template#64]
I didn't realize until this error popped up that docker containers were already in your project configuration. It has been a while since I looked at your repo. 

Please let me know how I can resolve the following issue and please let me know what exactly this docker maven plugin is doing. 

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.620 s
[INFO] Finished at: 2020-02-17T09:33:33-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.wouterdanes.docker:docker-maven-plugin:3.0:start-containers (start) on project maven-template: Execution start of goal net.wouterdanes.docker:docker-maven-plugin:3.0:start-containers failed: java.net.ConnectException: Connection refused (Connection refused) -> [Help 1]
[ERROR]

**Comment by Ardesco** [comment]
The wouterdanes docker-maven-plugin is out of date and will not work with the latest version of Docker (Docker has been a bit of a moving target over the years).  This is legacy code from the first edition of my book.

A newer revision of docker code (from the second edition of my book) is currently available here https://github.com/PacktPublishing/Mastering-Selenium-WebDriver-3.0-Second-Edition/tree/master/Chapter09

This is again out of date at the moment and probably needs to be updated again.

The code does various things, ranging from starting up a Selenium Grid, to running a container that hosts the code you are testing.

I'm unlikely to add any more docker code into this repo.  This is really designed to be a basic template to get all the basic boilerplate code down, which you can then add to.  It's not designed to be all things to all people.
