### ISSUE TITLE
How to run GoogleExampleIT

### ISSUE THREAD

**Issue by nurrochim** [Ardesco/Selenium-Maven-Template#66]
Hi... thanks for your attention

I'm a beginner on maven project, and I'm having a lot of trouble trying to run the sample test
I already try this code below, but nothing works :
- mvn clean verify
- mvn clean verify -Doverwrite.binaries=true
- mvn -Dit.test=GoogleExampleIT verify
- mvn -Dbrowser=chrome -Dit.test=GoogleExampleIT verify

this my command prompt capture
![2020-09-04_030400](https://user-images.githubusercontent.com/14324233/92161821-5e50a700-ee5b-11ea-903f-52560bfb82da.png)

thanks

**Comment by audirs4** [comment]
I just cloned the repo and ran it without issue. Did you make any changes to the project?

**Comment by nurrochim** [comment]
thanks @audirs4 
i have found the problem, its actualy the same issue like this one
https://github.com/Ardesco/driver-binary-downloader-maven-plugin/issues/11

thanks for your answer
