### ISSUE TITLE
Add Selenium methods in Java

### ISSUE THREAD

**Issue by VikasVashisth** [Ardesco/Selenium-Maven-Template#70]
Can I add various methods like waits , refresh and handle iframe in Selenium using java language with proper readme and use cases.

**Comment by Ardesco** [comment]
It's not really something that belongs in a template to kick off an automation project, but you can absolutely fork this and do that if you want to.  That being said all the information is available in the Selenium Docs:

- [https://www.selenium.dev/documentation/webdriver/waits/](https://www.selenium.dev/documentation/webdriver/waits/)
- [https://www.selenium.dev/documentation/webdriver/browser/frames/](https://www.selenium.dev/documentation/webdriver/browser/frames/)
- [https://www.selenium.dev/documentation/webdriver/browser/navigation/#refresh](https://www.selenium.dev/documentation/webdriver/browser/navigation/#refresh)
